// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAgency.DBMigrations;

#nullable disable

namespace RealEstateAgency.DBMigrations.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230913090947_AddRules")]
    partial class AddRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAgency.Models.AcessToActions", b =>
                {
                    b.Property<bool>("AcceptNewAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptNewWorker")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptOrdersClient")
                        .HasColumnType("bit");

                    b.Property<bool>("AddSalayWorkersForMonth")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherFirstName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherLastName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherSecondName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherUserId")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeAnotherUserName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourFirstName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourLastName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourSecondName")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangeYourUserName")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateService")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteClient")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteService")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteUser")
                        .HasColumnType("bit");

                    b.Property<bool>("DeleteWorker")
                        .HasColumnType("bit");

                    b.Property<bool>("EditService")
                        .HasColumnType("bit");

                    b.Property<bool>("FireAnEmployeAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("FireAnEmployeWorker")
                        .HasColumnType("bit");

                    b.Property<bool>("GetInformationYourSelf")
                        .HasColumnType("bit");

                    b.Property<bool>("GetListAllAdmins")
                        .HasColumnType("bit");

                    b.Property<bool>("GetListAllClients")
                        .HasColumnType("bit");

                    b.Property<bool>("GetListAllOrders")
                        .HasColumnType("bit");

                    b.Property<bool>("GetListAllWorkers")
                        .HasColumnType("bit");

                    b.Property<bool>("GetSalaryAnyWorkers")
                        .HasColumnType("bit");

                    b.Property<bool>("GetYourOrders")
                        .HasColumnType("bit");

                    b.Property<bool>("GiveRoleAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("GiveRoleClient")
                        .HasColumnType("bit");

                    b.Property<bool>("GiveRoleWorker")
                        .HasColumnType("bit");

                    b.Property<bool>("IneractionWithShifts")
                        .HasColumnType("bit");

                    b.Property<bool>("MakeAnyActions")
                        .HasColumnType("bit");

                    b.Property<bool>("SetScoreForOrders")
                        .HasColumnType("bit");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeAccount")
                        .HasColumnType("int");

                    b.HasIndex("UserIdUser");

                    b.ToTable("AcessToActions");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("UserIdUser");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Client", b =>
                {
                    b.Property<int>("IDClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDClient"));

                    b.Property<int>("CountPurchasedServices")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserIDUser")
                        .HasColumnType("int");

                    b.HasKey("IDClient");

                    b.HasIndex("UserIDUser");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Order", b =>
                {
                    b.Property<int>("IDOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOrder"));

                    b.Property<int>("ClientIDClient")
                        .HasColumnType("int");

                    b.Property<string>("DesriptionForCompletedOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOrderAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegularCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("OrderDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price_Service")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublishedOrder")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreForWork")
                        .HasColumnType("int");

                    b.Property<int>("ServiceIDService")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkerIDWorker")
                        .HasColumnType("int");

                    b.HasKey("IDOrder");

                    b.HasIndex("ClientIDClient");

                    b.HasIndex("ServiceIDService");

                    b.HasIndex("WorkerIDWorker");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("RealEstateAgency.Models.ReportProblems", b =>
                {
                    b.Property<string>("CommentAnAccess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDReport")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("bit");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasIndex("UserIdUser");

                    b.ToTable("ReportProblems");
                });

            modelBuilder.Entity("RealEstateAgency.Models.SalaryWorker", b =>
                {
                    b.Property<int>("IDSalary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSalary"));

                    b.Property<int>("DaysPlanWorked")
                        .HasColumnType("int");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Month")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncomeTaxPercentage")
                        .HasColumnType("int");

                    b.Property<double>("OnHand")
                        .HasColumnType("float");

                    b.Property<int>("PremiumPercentage")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.Property<int>("SalesPlan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_Month")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerIDWorker")
                        .HasColumnType("int");

                    b.HasKey("IDSalary");

                    b.HasIndex("WorkerIDWorker");

                    b.ToTable("SalaryWorker");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Service", b =>
                {
                    b.Property<int>("IDService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDService"));

                    b.Property<string>("DescriptionService")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameService")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("PriceService")
                        .HasColumnType("float");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDService");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Shift", b =>
                {
                    b.Property<int>("IDShift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDShift"));

                    b.Property<DateTime?>("EndShift")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartShift")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerIDWorker")
                        .HasColumnType("int");

                    b.HasKey("IDShift");

                    b.HasIndex("WorkerIDWorker");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("RealEstateAgency.Models.User", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(311)
                        .HasColumnType("nvarchar(311)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TokenRecovery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Worker", b =>
                {
                    b.Property<int>("IDWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDWorker"));

                    b.Property<DateTime?>("End_Date_To_Work")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RightCRUAccountant")
                        .HasColumnType("bit");

                    b.Property<bool>("RightChangeWorkers")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start_Date_To_Work")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserIDUser")
                        .HasColumnType("int");

                    b.HasKey("IDWorker");

                    b.HasIndex("UserIDUser");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("RealEstateAgency.Models.AcessToActions", b =>
                {
                    b.HasOne("RealEstateAgency.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Admin", b =>
                {
                    b.HasOne("RealEstateAgency.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Client", b =>
                {
                    b.HasOne("RealEstateAgency.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Order", b =>
                {
                    b.HasOne("RealEstateAgency.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientIDClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateAgency.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceIDService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateAgency.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerIDWorker");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RealEstateAgency.Models.ReportProblems", b =>
                {
                    b.HasOne("RealEstateAgency.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAgency.Models.SalaryWorker", b =>
                {
                    b.HasOne("RealEstateAgency.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerIDWorker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Shift", b =>
                {
                    b.HasOne("RealEstateAgency.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerIDWorker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RealEstateAgency.Models.Worker", b =>
                {
                    b.HasOne("RealEstateAgency.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIDUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
